### ISSUE TITLE
Saving on 1.2.0 causes all results to multiply

### ISSUE THREAD

**Issue by Glassound** [jessebarocio/Wox.Plugin.Runner#2]
After saving preferences on Wox 1.2.0 beta all results (even unrelated to Runner) are multiplied

**Comment by jessebarocio** [comment]
I'm not sure I understand. You mentioned it occurs with things unrelated to the Runner plugin. Does the issue occur when with the Runner plugin uninstalled? If so it is a bug in the Wox beta, please report it on the [Wox repo](https://github.com/qianlifeng/wox/issues). If not please provide exact steps to duplicate the problem.

**Comment by jessebarocio** [comment]
Stale issue.
