### ISSUE TITLE
System.NullReferenceException in Wox.Plugin.Runner

### ISSUE THREAD

**Issue by Wishmaster172** [jessebarocio/Wox.Plugin.Runner#7]
Hi,

there's a problem in the Runner Plugin. Everytime I type the shortcut "r" and just space and one single letter, I get this exception:

bei Wox.Plugin.Runner.Runner.<>c__DisplayClass6.b__3(Command c)
bei System.Linq.Enumerable.WhereSelectListIterator2.MoveNext() bei System.Collections.Generic.List1.InsertRange(Int32 index, IEnumerable1 collection) bei System.Collections.Generic.List1.AddRange(IEnumerable`1 collection)
bei Wox.Plugin.Runner.Runner.Query(Query query)
bei Wox.Core.Plugin.PluginManager.<>c__DisplayClass30_0.b__0() in C:\Users\Ricky\Documents\GitHub\Wox\Wox.Core\Plugin\PluginManager.cs:Zeile 192.
bei Wox.Infrastructure.Stopwatch.Normal(String name, Action action) in C:\Users\Ricky\Documents\GitHub\Wox\Wox.Infrastructure\Stopwatch.cs:Zeile 28.
bei Wox.Core.Plugin.PluginManager.QueryForPlugin(PluginPair pair, Query query) in C:\Users\Ricky\Documents\GitHub\Wox\Wox.Core\Plugin\PluginManager.cs:Zeile 190.
Can someone help, please?

Best regards,
Steffen

**Comment by jessebarocio** [comment]
Hello @Wishmaster172 

I am unable to duplicate this problem. My best guess is that you have a command with an empty **Shortcut** or **Path** property. Can you please check your settings and fix or delete any commands without Shortcuts or Paths?

**Comment by Wishmaster172** [comment]
Hi @jessebarocio,

you were right, there is a command with an empty shortcut in the list. But if I try to change/delete this one I get an error on saving:

![2016-06-15 11_52_57-wox got an error](https://cloud.githubusercontent.com/assets/17496386/16075627/fdacfb18-32ef-11e6-8320-755f6f21c3ed.png)

Best regards

**Comment by jessebarocio** [comment]
@Wishmaster172 That error was reported in #8 . The plugin was written using an older version of the Wox API. I have a fix and will be publishing an update later today.

In the meantime you can manually remove the broken command from %LocalAppData%\Wox.Plugin.Runner\commands.json.

**Comment by happlebao** [comment]
@jessebarocio may I ask why you need reload plugins there?
https://github.com/jessebarocio/Wox.Plugin.Runner/blob/master/Wox.Plugin.Runner/Settings/RunnerSettingsViewModel.cs#L118

**Comment by jessebarocio** [comment]
@happlebao I don't. I'm not sure why that was in the original code but I have removed it in my latest changes. Thanks for publishing the nuget package.

**Comment by jessebarocio** [comment]
Hello @Wishmaster172, I have updated the plugin. You can run this command to get the latest version:

    wpm install Wox.Plugin.Runner

**Comment by jessebarocio** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;OKbus8Xg&#x2F;2-as-a-user-i-want-to-see-a-list-of-all-legislators-on-my-phone"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> As a user I want to see a list of all legislators on my phone.</a>
